[package]
name = "chat-analyse"
version = "0.1.0"
authors = ["Dravid Kumar <dravidkumars@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
regex = "1"
chrono = "0.4"
